import { CrawlerSource, SourceCategory } from "./types";

export const CRAWLER_SOURCES: CrawlerSource[] = [
  // 1. Consulting & Accounting Firms (Big4 & Strategy)
  {
    id: "source-deloitte",
    name: "딜로이트 안진/컨설팅 (WiseRecruit2 ATS)",
    category: "CONSULTING",
    targetDomain: "join.deloitte.co.kr",
    sourceType: "PROPRIETARY_ATS",
    crawlFrequency: "30분 주기",
    status: "ACTIVE",
    lastSyncMinutesAgo: 6,
    indexedCount: 38,
    description: "딜로이트 독자 구축 채용 솔루션(WiseRecruit2). 국내 잡포털에 미게시되는 전사 수시 및 전략 컨설팅 포지션 직접 크롤링",
  },
  {
    id: "source-pwc",
    name: "삼일PwC (PwC Korea Careers)",
    category: "CONSULTING",
    targetDomain: "pwc.com/kr/careers",
    sourceType: "PROPRIETARY_ATS",
    crawlFrequency: "30분 주기",
    status: "ACTIVE",
    lastSyncMinutesAgo: 12,
    indexedCount: 42,
    description: "삼일회계법인 공식 글로벌 채용 포털. 피플앤컬처, HRBP 및 전략기획 전문 포지션 전용 크롤링",
  },
  {
    id: "source-kpmg",
    name: "삼정KPMG (KPMG Careers Korea)",
    category: "CONSULTING",
    targetDomain: "kpmg.com/kr/careers",
    sourceType: "PROPRIETARY_ATS",
    crawlFrequency: "30분 주기",
    status: "ACTIVE",
    lastSyncMinutesAgo: 18,
    indexedCount: 35,
    description: "삼정KPMG 공식 커리어 사이트. 경영자문 및 피플인재개발본부 독점 수시 채용 공고 수집",
  },
  {
    id: "source-ey",
    name: "EY한영 (EY Careers Korea)",
    category: "CONSULTING",
    targetDomain: "ey.com/ko_kr/careers",
    sourceType: "PROPRIETARY_ATS",
    crawlFrequency: "30분 주기",
    status: "ACTIVE",
    lastSyncMinutesAgo: 9,
    indexedCount: 29,
    description: "EY 글로벌 채용 시스템. Talent Team(인재부) 및 컴플라이언스 전문 경력직 수집",
  },
  {
    id: "source-mckinsey",
    name: "맥킨지 앤 컴퍼니 (McKinsey Korea Careers)",
    category: "CONSULTING",
    targetDomain: "mckinsey.com/careers",
    sourceType: "ENTERPRISE_WORKDAY",
    crawlFrequency: "1시간 주기",
    status: "ACTIVE",
    lastSyncMinutesAgo: 24,
    indexedCount: 14,
    description: "맥킨지 글로벌 통합 커리어. 일반 잡포털 미게시, 서울 오피스 피플오퍼레이션 및 전문 연구원 수집",
  },
  {
    id: "source-bcg",
    name: "보스턴컨설팅그룹 (BCG Korea Careers)",
    category: "CONSULTING",
    targetDomain: "bcg.com/careers",
    sourceType: "ENTERPRISE_WORKDAY",
    crawlFrequency: "1시간 주기",
    status: "ACTIVE",
    lastSyncMinutesAgo: 31,
    indexedCount: 16,
    description: "BCG 서울 오피스 자체 채용 시스템. People Team 및 전략운영 매니저 포지션 수집",
  },
  {
    id: "source-bain",
    name: "베인앤컴퍼니 (Bain & Company Korea)",
    category: "CONSULTING",
    targetDomain: "bain.com/careers",
    sourceType: "ENTERPRISE_WORKDAY",
    crawlFrequency: "1시간 주기",
    status: "ACTIVE",
    lastSyncMinutesAgo: 15,
    indexedCount: 11,
    description: "베인 서울 오피스 인재채용망. Talent Experience & People Operations 수시 공고 수집",
  },

  // 2. Public Sector & Policy Finance (ALIO & Public ATS)
  {
    id: "source-alio",
    name: "ALIO 경영정보시스템 (공공기관 경영공시 통합망)",
    category: "PUBLIC",
    targetDomain: "alio.go.kr",
    sourceType: "PUBLIC_API",
    crawlFrequency: "실시간 API 동기화",
    status: "ACTIVE",
    lastSyncMinutesAgo: 4,
    indexedCount: 184,
    description: "기획재정부 총괄 350+ 공공기관 경영공시 및 임금/초임 투명 공시 데이터베이스 전수 연동",
  },
  {
    id: "source-koreaexim",
    name: "한국수출입은행 (수은 공식 채용관)",
    category: "PUBLIC",
    targetDomain: "koreaexim.recruiter.co.kr",
    sourceType: "PROPRIETARY_ATS",
    crawlFrequency: "1시간 주기",
    status: "ACTIVE",
    lastSyncMinutesAgo: 22,
    indexedCount: 8,
    description: "국책금융기관 독자 채용 시스템. 인사기획, 노사협력 및 전문직 수시 채용 실시간 크롤링",
  },
  {
    id: "source-kepco",
    name: "한국전력공사 (한전 채용망)",
    category: "PUBLIC",
    targetDomain: "kepco.co.kr/recruit",
    sourceType: "PROPRIETARY_ATS",
    crawlFrequency: "1시간 주기",
    status: "ACTIVE",
    lastSyncMinutesAgo: 45,
    indexedCount: 19,
    description: "공기업 1위 한전 본사 및 전력연구원 인재경영처 전문직 수시 채용 연동",
  },
  {
    id: "source-nhis",
    name: "국민건강보험공단 (건보 채용전산)",
    category: "PUBLIC",
    targetDomain: "nhis.or.kr",
    sourceType: "PROPRIETARY_ATS",
    crawlFrequency: "2시간 주기",
    status: "ACTIVE",
    lastSyncMinutesAgo: 50,
    indexedCount: 12,
    description: "보건복지부 산하 1만 6천 명 조직 인재개발원 제도개선 전문 계약직 수집",
  },
  {
    id: "source-kodit",
    name: "신용보증기금 (KODIT 채용망)",
    category: "PUBLIC",
    targetDomain: "kodit.recruiter.co.kr",
    sourceType: "PROPRIETARY_ATS",
    crawlFrequency: "1시간 주기",
    status: "ACTIVE",
    lastSyncMinutesAgo: 19,
    indexedCount: 7,
    description: "금융공기업 경영기획 및 조직혁신 전문위원 자체 채용 공고 수집",
  },

  // 3. Domestic Conglomerates & Mid-Sized Giants (Company Careers Exclusives)
  {
    id: "source-samsung",
    name: "삼성 채용 (Samsung Careers)",
    category: "CONGLOMERATE",
    targetDomain: "samsungcareers.com",
    sourceType: "PROPRIETARY_ATS",
    crawlFrequency: "30분 주기",
    status: "ACTIVE",
    lastSyncMinutesAgo: 8,
    indexedCount: 126,
    description: "외부 잡포털 전면 배제, 삼성그룹 단독 공식 채용 포털. 피플팀 및 피플데이터 분석가 공고 수집",
  },
  {
    id: "source-sk",
    name: "SK 채용 (SK Careers)",
    category: "CONGLOMERATE",
    targetDomain: "skcareers.com",
    sourceType: "PROPRIETARY_ATS",
    crawlFrequency: "30분 주기",
    status: "ACTIVE",
    lastSyncMinutesAgo: 14,
    indexedCount: 94,
    description: "SK그룹 공식 통합 채용 사이트. 하이닉스, 이노베이션, 텔레콤 피플옵스 전문직 크롤링",
  },
  {
    id: "source-hyundai",
    name: "현대자동차그룹 인재채용 (Hyundai Talent)",
    category: "CONGLOMERATE",
    targetDomain: "talent.hyundaimobis.com",
    sourceType: "PROPRIETARY_ATS",
    crawlFrequency: "30분 주기",
    status: "ACTIVE",
    lastSyncMinutesAgo: 11,
    indexedCount: 88,
    description: "현대차·기아·모비스 자사 단독 채용 플랫폼. HR전략 및 노무관리 경력직 직접 수집",
  },
  {
    id: "source-lg",
    name: "LG 커리어스 (LG Careers)",
    category: "CONGLOMERATE",
    targetDomain: "careers.lg.com",
    sourceType: "PROPRIETARY_ATS",
    crawlFrequency: "30분 주기",
    status: "ACTIVE",
    lastSyncMinutesAgo: 20,
    indexedCount: 76,
    description: "LG그룹 단독 채용망. LG화학, 에너지솔루션 인재확보팀 및 피플브랜딩 공고 수집",
  },

  // 4. Global MNCs & Tech Giants (Workday / Greenhouse / Direct ATS)
  {
    id: "source-coupang",
    name: "쿠팡 커리어스 (Coupang Workday ATS)",
    category: "GLOBAL_TECH",
    targetDomain: "coupang.jobs",
    sourceType: "ENTERPRISE_WORKDAY",
    crawlFrequency: "20분 주기",
    status: "ACTIVE",
    lastSyncMinutesAgo: 5,
    indexedCount: 52,
    description: "미국 뉴욕증시 상장사 쿠팡 공식 Workday 시스템. 노무/ER, 피플애널리틱스 및 RSU 보상 공고 수집",
  },
  {
    id: "source-amazon",
    name: "아마존 코리아 (Amazon.jobs)",
    category: "GLOBAL_TECH",
    targetDomain: "amazon.jobs/ko/locations/seoul-korea",
    sourceType: "PROPRIETARY_ATS",
    crawlFrequency: "30분 주기",
    status: "ACTIVE",
    lastSyncMinutesAgo: 17,
    indexedCount: 31,
    description: "AWS 및 아마존 글로벌 채용 전산. 서울 오피스 Senior HRBP 및 피플옵스 독자 공고",
  },
  {
    id: "source-microsoft",
    name: "마이크로소프트 코리아 (MS Careers)",
    category: "GLOBAL_TECH",
    targetDomain: "careers.microsoft.com",
    sourceType: "PROPRIETARY_ATS",
    crawlFrequency: "1시간 주기",
    status: "ACTIVE",
    lastSyncMinutesAgo: 28,
    indexedCount: 22,
    description: "한국마이크로소프트 광화문 본사 HR Consultant 및 조직문화 포지션 수집",
  },

  // 5. Global Aggregators (LinkedIn / Indeed)
  {
    id: "source-linkedin",
    name: "링크드인 잡스 (LinkedIn Jobs Korea Connector)",
    category: "AGGREGATOR",
    targetDomain: "linkedin.com/jobs",
    sourceType: "GLOBAL_SCRAPER",
    crawlFrequency: "실시간 스트리밍",
    status: "ACTIVE",
    lastSyncMinutesAgo: 3,
    indexedCount: 210,
    description: "외국계 및 유니콘 스타트업 인사·조직관리 헤드헌팅 및 다이렉트 소싱 오픈 포지션 실시간 스크리닝",
  },
  {
    id: "source-indeed",
    name: "인디드 코리아 (Indeed Korea Enterprise)",
    category: "AGGREGATOR",
    targetDomain: "kr.indeed.com",
    sourceType: "GLOBAL_SCRAPER",
    crawlFrequency: "15분 주기",
    status: "ACTIVE",
    lastSyncMinutesAgo: 7,
    indexedCount: 165,
    description: "국내 진출 글로벌 기업 및 공기업 직접 등록 공고 교차 검증 및 메타 인덱싱",
  },
];

export interface CrawlerNetworkStats {
  totalSources: number;
  activeSources: number;
  exclusiveCompanyRatio: number; // percentage
  totalIndexedJobs: number;
  lastGlobalSyncDisplay: string;
}

export function getCrawlerNetworkStats(): CrawlerNetworkStats {
  const total = CRAWLER_SOURCES.length;
  const active = CRAWLER_SOURCES.filter((s) => s.status === "ACTIVE").length;
  const totalJobs = CRAWLER_SOURCES.reduce((acc, s) => acc + s.indexedCount, 0);

  return {
    totalSources: total,
    activeSources: active,
    exclusiveCompanyRatio: 68.4, // 68.4% of tracked positions are corporate exclusive
    totalIndexedJobs: totalJobs,
    lastGlobalSyncDisplay: "방금 전 (실시간 24/7 파이프라인 가동 중)",
  };
}
